### ISSUE TITLE
PDF auto-downloads without warning

### ISSUE THREAD

**Issue by carowa** [katiegoulding/food-access-vashon#22]
Current behavior: on 'generate buck set' the set is created and opens in browser and downloads locally without a prompt.
Correct behavior: on 'generate buck set' the set is created and either opens in a new tab in the browser OR prompts for download locally

**Comment by NoobyScoob** [comment]
Hie, I want to help, could you please add some documentation about the project!
And about downloading pdf, you can simply pop up a model. Anchor tag with target _blank would do fine for the pdf to open in another window.
